### ISSUE TITLE
Build of validator

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#21]
@germa Apologies if I missed it somewhere - it's not obvious if there is a release of the validator available for developers. It would be good to post this on the front page of the mzIdentML GitHub, or at least have it available inside the Git repository. I'm struggling to locate it?

thanks
Andy

**Comment by andrewrobertjones** [comment]
@germa  Further note, I compiled this locally on Netbeans. When I try to run the validator, I get the following message:

`java.io.FileNotFoundException: E:\Work\PSI\mzIdentML\Git\validator\trunk\resources\validation.properties (The system can
not find the path specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at psidev.psi.pi.validator.PropertyFile.loadProperties(PropertyFile.java:36)
        at psidev.psi.pi.validator.MzIdentMLValidatorGUI.getProperty(MzIdentMLValidatorGUI.java:929)
        at psidev.psi.pi.validator.MzIdentMLValidatorGUI.getOntologiesFileInputStream(MzIdentMLValidatorGUI.java:757)
        at psidev.psi.pi.validator.MzIdentMLValidatorGUI.access$900(MzIdentMLValidatorGUI.java:58)
        at psidev.psi.pi.validator.MzIdentMLValidatorGUI$4.loadOntologyFiles(MzIdentMLValidatorGUI.java:723)
        at psidev.psi.pi.validator.MzIdentMLValidatorGUI$4.construct(MzIdentMLValidatorGUI.java:655)
        at psidev.psi.pi.validator.swingworker.SwingWorker$2.run(SwingWorker.java:147)
        at java.lang.Thread.run(Unknown Source)
2016-05-03 13:35:53,020 ERROR MzIdentMLValidatorGUI - No ontologies file for validation.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException`

**Comment by julianu** [comment]
@germa send this location for the validator around a while ago:
https://github.com/HUPO-PSI/mzIdentML/tree/master/validator/trunk/mzIdentMLValidator

Anyways, I would vote rather to have the running validator under the releases of the project instead inside of the code. There are already some old releases, created by @ypriverol during the move to gitHub, I guess.
It might be even cleaner to create a new project (HUPO-PSI/mzIdentMLValidator) for it and put the releases there?

**Comment by ypriverol** [comment]
@julianu I vote also for this option however should be clear from the readme of the file format where is the official validator. If you let me know where is the current version I can remove the old version and create the repository.

**Comment by andrewrobertjones** [comment]
Thanks all. I don't mind whether it is branched to a new project or stays here. The front page of the GitHub should make it really clear how everyone gets access to the latest validator though. When a new build is made, is it possible to tag is so it automatically appears somewhere?

**Comment by mwalzer** [comment]
In the telco I was referring to that: https://github.com/HUPO-PSI/psi-ms-CV/releases

**Comment by mwalzer** [comment]
I just saw that Yasset already built github releases for the validator :smiley:

So for a better accessibility, we would just have to update the releases and link to the release site from the repository start page.

**Comment by mwalzer** [comment]
I updated the release to the current and fixed the link on the start page to the release page. 
@germa if you could create a github release (https://github.com/HUPO-PSI/psi-ms-CV/releases/new) when you release a new version of the validator, welcome page will always point to the most recent validator.
