### ISSUE TITLE
Validator: null pointer for missing version number in the cvList

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#6]
I get the following null pointer when trying to run the validator on the PeptideShaker 1.2 example file:

```
Exception in thread "Thread-4" java.lang.NullPointerException
        at psidev.psi.pi.validator.objectrules.CvListObjectRule.check(CvListObjectRule.java:77)
        at psidev.psi.pi.validator.objectrules.CvListObjectRule.check(CvListObjectRule.java:21)
        at psidev.psi.pi.validator.MzIdentMLValidator.validate(MzIdentMLValidator.java:864)
        at psidev.psi.pi.validator.MzIdentMLValidator.checkElementObjectRule(MzIdentMLValidator.java:823)
        at psidev.psi.pi.validator.MzIdentMLValidator.applyObjectRules(MzIdentMLValidator.java:676)
        at psidev.psi.pi.validator.MzIdentMLValidator.doValidationWork(MzIdentMLValidator.java:447)
        at psidev.psi.pi.validator.MzIdentMLValidator.startValidation(MzIdentMLValidator.java:417)
        at psidev.psi.pi.validator.MzIdentMLValidatorGUI$4.construct(MzIdentMLValidatorGUI.java:675)
        at psidev.psi.pi.validator.swingworker.SwingWorker$2.run(SwingWorker.java:147)
        at java.lang.Thread.run(Unknown Source)
```

The problem seems to be that the validator requires a version number for the elements in the cvList, but as far as I can tell the version number is not mandatory here?

I think it can all be easily fixed by checking if the versions number is not null before using the version object?

@germa Can you take a look at this one?

**Comment by germa** [comment]
Should be fixed now.

**Comment by germa** [comment]
Should be fixed now.
