### ISSUE TITLE
Validator throws error if optional <AdditionalSearchParams> is missing

### ISSUE THREAD

**Issue by mhoopmann** [HUPO-PSI/mzIdentML#85]
According to the schema AdditionalSearchParams is an optional element of SpectrumIdentificationProtocol.

However, if AdditionalSearchParams is not specified, I get the following exception:
Exception in thread "Thread-5" java.lang.NullPointerException
        at psidev.psi.pi.validator.objectrules.AdditionalSearchParamsObjectRule.check(AdditionalSearchParamsObjectRule.java:81)
        at psidev.psi.pi.validator.objectrules.AdditionalSearchParamsObjectRule.check(AdditionalSearchParamsObjectRule.java:21)
        at psidev.psi.pi.validator.MzIdentMLValidator.validate(MzIdentMLValidator.java:1052)
        at psidev.psi.pi.validator.MzIdentMLValidator.checkElementObjectRule(MzIdentMLValidator.java:1011)
        at psidev.psi.pi.validator.MzIdentMLValidator.applyObjectRules(MzIdentMLValidator.java:817)
        at psidev.psi.pi.validator.MzIdentMLValidator.doValidationWork(MzIdentMLValidator.java:588)
        at psidev.psi.pi.validator.MzIdentMLValidator.startValidation(MzIdentMLValidator.java:500)
        at psidev.psi.pi.validator.MzIdentMLValidatorGUI$4.construct(MzIdentMLValidatorGUI.java:685)
        at psidev.psi.pi.validator.swingworker.SwingWorker.lambda$new$1(SwingWorker.java:138)
        at java.lang.Thread.run(Unknown Source)

I am using java 8 update 121 (64-bit) on windows 7.

**Comment by smdb21** [comment]
We should solve this by changing AdditionalSearchParamsObjectRule.java introducing a null check, from:
```
public Collection<ValidatorMessage> check(SpectrumIdentificationProtocol sip) throws ValidatorException {
        List<ValidatorMessage> messages = new ArrayList<>();

        // check for the special processing types
        int cnt = 0;
        for (CvParam cvp: sip.getAdditionalSearchParams().getCvParam()) {

```
to
```
public Collection<ValidatorMessage> check(SpectrumIdentificationProtocol sip) throws ValidatorException {
        List<ValidatorMessage> messages = new ArrayList<>();

        // check for the special processing types
        int cnt = 0;
       if (sip !=null && sip.getAdditionalSearchParams() != null && sip.getAdditionalSearchParams().getCvParams() != null ) {
        for (CvParam cvp: sip.getAdditionalSearchParams().getCvParam()) {
```

**Comment by germa** [comment]
Solved in mzIdentMLValidator_GUI_v1.4.31-SNAPSHOT
